'\" t
.\"     Title: apt-ftparchive
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09\ \&June\ \&2012
.\"    Manual: APT
.\"    Source: APT 1.0.6
.\"  Language: English
.\"
.TH "APT\-FTPARCHIVE" "1" "09\ \&June\ \&2012" "APT 1.0.6" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt-ftparchive \- Utility to generate index files
.SH "SYNOPSIS"
.HP \w'\fBapt\-ftparchive\fR\ 'u
\fBapt\-ftparchive\fR [\fB\-dsq\fR] [\fB\-\-md5\fR] [\fB\-\-delink\fR] [\fB\-\-readonly\fR] [\fB\-\-contents\fR] [\fB\-\-arch\ \fR\fB\fIarchitecture\fR\fR] [\fB\-o=\fR\fB\fIconfig_string\fR\fR] [\fB\-c=\fR\fB\fIconfig_file\fR\fR] {packages\ \fIpath\fR...\ [\fIoverride\-file\fR\ [\fIpathprefix\fR]]  | sources\ \fIpath\fR...\ [\fIoverride\-file\fR\ [\fIpathprefix\fR]]  | contents\ \fIpath\fR  | release\ \fIpath\fR  | generate\ \fIconfig_file\fR\ \fIsection\fR...  | clean\ \fIconfig_file\fR  | {\-v\ |\ \-\-version} | {\-h\ |\ \-\-help}}
.SH "DESCRIPTION"
.PP
\fBapt\-ftparchive\fR
is the command line tool that generates the index files that APT uses to access a distribution source\&. The index files should be generated on the origin site based on the content of that site\&.
.PP
\fBapt\-ftparchive\fR
is a superset of the
\fBdpkg-scanpackages\fR(1)
program, incorporating its entire functionality via the
packages
command\&. It also contains a contents file generator,
contents, and an elaborate means to \*(Aqscript\*(Aq the generation process for a complete archive\&.
.PP
Internally
\fBapt\-ftparchive\fR
can make use of binary databases to cache the contents of a \&.deb file and it does not rely on any external programs aside from
\fBgzip\fR(1)\&. When doing a full generate it automatically performs file\-change checks and builds the desired compressed output files\&.
.PP
Unless the
\fB\-h\fR, or
\fB\-\-help\fR
option is given, one of the commands below must be present\&.
.PP
\fBpackages\fR
.RS 4
The packages command generates a package file from a directory tree\&. It takes the given directory and recursively searches it for \&.deb files, emitting a package record to stdout for each\&. This command is approximately equivalent to
\fBdpkg-scanpackages\fR(1)\&.
.sp
The option
\fB\-\-db\fR
can be used to specify a binary caching DB\&.
.RE
.PP
\fBsources\fR
.RS 4
The
sources
command generates a source index file from a directory tree\&. It takes the given directory and recursively searches it for \&.dsc files, emitting a source record to stdout for each\&. This command is approximately equivalent to
\fBdpkg-scansources\fR(1)\&.
.sp
If an override file is specified then a source override file will be looked for with an extension of \&.src\&. The \-\-source\-override option can be used to change the source override file that will be used\&.
.RE
.PP
\fBcontents\fR
.RS 4
The
contents
command generates a contents file from a directory tree\&. It takes the given directory and recursively searches it for \&.deb files, and reads the file list from each file\&. It then sorts and writes to stdout the list of files matched to packages\&. Directories are not written to the output\&. If multiple packages own the same file then each package is separated by a comma in the output\&.
.sp
The option
\fB\-\-db\fR
can be used to specify a binary caching DB\&.
.RE
.PP
\fBrelease\fR
.RS 4
The
release
command generates a Release file from a directory tree\&. It recursively searches the given directory for uncompressed
Packages
and
Sources
files and ones compressed with
\fBgzip\fR,
\fBbzip2\fR
or
\fBlzma\fR
as well as
Release
and
md5sum\&.txt
files by default (APT::FTPArchive::Release::Default\-Patterns)\&. Additional filename patterns can be added by listing them in
APT::FTPArchive::Release::Patterns\&. It then writes to stdout a
Release
file containing an MD5, SHA1 and SHA256 digest for each file\&.
.sp
Values for the additional metadata fields in the Release file are taken from the corresponding variables under
APT::FTPArchive::Release, e\&.g\&.
APT::FTPArchive::Release::Origin\&. The supported fields are:
Origin,
Label,
Suite,
Version,
Codename,
Date,
Valid\-Until,
Architectures,
Components,
Description\&.
.RE
.PP
\fBgenerate\fR
.RS 4
The
generate
command is designed to be runnable from a cron script and builds indexes according to the given config file\&. The config language provides a flexible means of specifying which index files are built from which directories, as well as providing a simple means of maintaining the required settings\&.
.RE
.PP
\fBclean\fR
.RS 4
The
clean
command tidies the databases used by the given configuration file by removing any records that are no longer necessary\&.
.RE
.SH "THE GENERATE CONFIGURATION"
.PP
The
generate
command uses a configuration file to describe the archives that are going to be generated\&. It follows the typical ISC configuration format as seen in ISC tools like bind 8 and dhcpd\&.
\fBapt.conf\fR(5)
contains a description of the syntax\&. Note that the generate configuration is parsed in sectional manner, but
\fBapt.conf\fR(5)
is parsed in a tree manner\&. This only effects how the scope tag is handled\&.
.PP
The generate configuration has four separate sections, each described below\&.
.SS "Dir Section"
.PP
The
Dir
section defines the standard directories needed to locate the files required during the generation process\&. These directories are prepended certain relative paths defined in later sections to produce a complete an absolute path\&.
.PP
\fBArchiveDir\fR
.RS 4
Specifies the root of the FTP archive, in a standard Debian configuration this is the directory that contains the
ls\-LR
and dist nodes\&.
.RE
.PP
\fBOverrideDir\fR
.RS 4
Specifies the location of the override files\&.
.RE
.PP
\fBCacheDir\fR
.RS 4
Specifies the location of the cache files\&.
.RE
.PP
\fBFileListDir\fR
.RS 4
Specifies the location of the file list files, if the
FileList
setting is used below\&.
.RE
.SS "Default Section"
.PP
The
Default
section specifies default values, and settings that control the operation of the generator\&. Other sections may override these defaults with a per\-section setting\&.
.PP
\fBPackages::Compress\fR
.RS 4
Sets the default compression schemes to use for the package index files\&. It is a string that contains a space separated list of at least one of: \*(Aq\&.\*(Aq (no compression), \*(Aqgzip\*(Aq and \*(Aqbzip2\*(Aq\&. The default for all compression schemes is \*(Aq\&. gzip\*(Aq\&.
.RE
.PP
\fBPackages::Extensions\fR
.RS 4
Sets the default list of file extensions that are package files\&. This defaults to \*(Aq\&.deb\*(Aq\&.
.RE
.PP
\fBSources::Compress\fR
.RS 4
This is similar to
Packages::Compress
except that it controls the compression for the Sources files\&.
.RE
.PP
\fBSources::Extensions\fR
.RS 4
Sets the default list of file extensions that are source files\&. This defaults to \*(Aq\&.dsc\*(Aq\&.
.RE
.PP
\fBContents::Compress\fR
.RS 4
This is similar to
Packages::Compress
except that it controls the compression for the Contents files\&.
.RE
.PP
\fBTranslation::Compress\fR
.RS 4
This is similar to
Packages::Compress
except that it controls the compression for the Translation\-en master file\&.
.RE
.PP
\fBDeLinkLimit\fR
.RS 4
Specifies the number of kilobytes to delink (and replace with hard links) per run\&. This is used in conjunction with the per\-section
External\-Links
setting\&.
.RE
.PP
\fBFileMode\fR
.RS 4
Specifies the mode of all created index files\&. It defaults to 0644\&. All index files are set to this mode with no regard to the umask\&.
.RE
.PP
\fBLongDescription\fR
.RS 4
Specifies whether long descriptions should be included in the
Packages
file or split out into a master
Translation\-en
file\&.
.RE
.SS "TreeDefault Section"
.PP
Sets defaults specific to
Tree
sections\&. All of these variables are substitution variables and have the strings $(DIST), $(SECTION) and $(ARCH) replaced with their respective values\&.
.PP
\fBMaxContentsChange\fR
.RS 4
Sets the number of kilobytes of contents files that are generated each day\&. The contents files are round\-robined so that over several days they will all be rebuilt\&.
.RE
.PP
\fBContentsAge\fR
.RS 4
Controls the number of days a contents file is allowed to be checked without changing\&. If this limit is passed the mtime of the contents file is updated\&. This case can occur if the package file is changed in such a way that does not result in a new contents file [override edit for instance]\&. A hold off is allowed in hopes that new \&.debs will be installed, requiring a new file anyhow\&. The default is 10, the units are in days\&.
.RE
.PP
\fBDirectory\fR
.RS 4
Sets the top of the \&.deb directory tree\&. Defaults to
$(DIST)/$(SECTION)/binary\-$(ARCH)/
.RE
.PP
\fBSrcDirectory\fR
.RS 4
Sets the top of the source package directory tree\&. Defaults to
$(DIST)/$(SECTION)/source/
.RE
.PP
\fBPackages\fR
.RS 4
Sets the output Packages file\&. Defaults to
$(DIST)/$(SECTION)/binary\-$(ARCH)/Packages
.RE
.PP
\fBSources\fR
.RS 4
Sets the output Sources file\&. Defaults to
$(DIST)/$(SECTION)/source/Sources
.RE
.PP
\fBTranslation\fR
.RS 4
Sets the output Translation\-en master file with the long descriptions if they should be not included in the Packages file\&. Defaults to
$(DIST)/$(SECTION)/i18n/Translation\-en
.RE
.PP
\fBInternalPrefix\fR
.RS 4
Sets the path prefix that causes a symlink to be considered an internal link instead of an external link\&. Defaults to
$(DIST)/$(SECTION)/
.RE
.PP
\fBContents\fR
.RS 4
Sets the output Contents file\&. Defaults to
$(DIST)/$(SECTION)/Contents\-$(ARCH)\&. If this setting causes multiple Packages files to map onto a single Contents file (as is the default) then
\fBapt\-ftparchive\fR
will integrate those package files together automatically\&.
.RE
.PP
\fBContents::Header\fR
.RS 4
Sets header file to prepend to the contents output\&.
.RE
.PP
\fBBinCacheDB\fR
.RS 4
Sets the binary cache database to use for this section\&. Multiple sections can share the same database\&.
.RE
.PP
\fBFileList\fR
.RS 4
Specifies that instead of walking the directory tree,
\fBapt\-ftparchive\fR
should read the list of files from the given file\&. Relative files names are prefixed with the archive directory\&.
.RE
.PP
\fBSourceFileList\fR
.RS 4
Specifies that instead of walking the directory tree,
\fBapt\-ftparchive\fR
should read the list of files from the given file\&. Relative files names are prefixed with the archive directory\&. This is used when processing source indexes\&.
.RE
.SS "Tree Section"
.PP
The
Tree
section defines a standard Debian file tree which consists of a base directory, then multiple sections in that base directory and finally multiple Architectures in each section\&. The exact pathing used is defined by the
Directory
substitution variable\&.
.PP
The
Tree
section takes a scope tag which sets the
$(DIST)
variable and defines the root of the tree (the path is prefixed by
ArchiveDir)\&. Typically this is a setting such as
dists/wheezy\&.
.PP
All of the settings defined in the
TreeDefault
section can be used in a
Tree
section as well as three new variables\&.
.PP
When processing a
Tree
section
\fBapt\-ftparchive\fR
performs an operation similar to:
.sp
.if n \{\
.RS 4
.\}
.nf
for i in Sections do 
   for j in Architectures do
      Generate for DIST=scope SECTION=i ARCH=j
     
.fi
.if n \{\
.RE
.\}

.PP
\fBSections\fR
.RS 4
This is a space separated list of sections which appear under the distribution; typically this is something like
main contrib non\-free
.RE
.PP
\fBArchitectures\fR
.RS 4
This is a space separated list of all the architectures that appear under search section\&. The special architecture \*(Aqsource\*(Aq is used to indicate that this tree has a source archive\&.
.RE
.PP
\fBLongDescription\fR
.RS 4
Specifies whether long descriptions should be included in the
Packages
file or split out into a master
Translation\-en
file\&.
.RE
.PP
\fBBinOverride\fR
.RS 4
Sets the binary override file\&. The override file contains section, priority and maintainer address information\&.
.RE
.PP
\fBSrcOverride\fR
.RS 4
Sets the source override file\&. The override file contains section information\&.
.RE
.PP
\fBExtraOverride\fR
.RS 4
Sets the binary extra override file\&.
.RE
.PP
\fBSrcExtraOverride\fR
.RS 4
Sets the source extra override file\&.
.RE
.SS "BinDirectory Section"
.PP
The
bindirectory
section defines a binary directory tree with no special structure\&. The scope tag specifies the location of the binary directory and the settings are similar to the
Tree
section with no substitution variables or
SectionArchitecture
settings\&.
.PP
\fBPackages\fR
.RS 4
Sets the Packages file output\&.
.RE
.PP
\fBSources\fR
.RS 4
Sets the Sources file output\&. At least one of
Packages
or
Sources
is required\&.
.RE
.PP
\fBContents\fR
.RS 4
Sets the Contents file output (optional)\&.
.RE
.PP
\fBBinOverride\fR
.RS 4
Sets the binary override file\&.
.RE
.PP
\fBSrcOverride\fR
.RS 4
Sets the source override file\&.
.RE
.PP
\fBExtraOverride\fR
.RS 4
Sets the binary extra override file\&.
.RE
.PP
\fBSrcExtraOverride\fR
.RS 4
Sets the source extra override file\&.
.RE
.PP
\fBBinCacheDB\fR
.RS 4
Sets the cache DB\&.
.RE
.PP
\fBPathPrefix\fR
.RS 4
Appends a path to all the output paths\&.
.RE
.PP
\fBFileList\fR, \fBSourceFileList\fR
.RS 4
Specifies the file list file\&.
.RE
.SH "THE BINARY OVERRIDE FILE"
.PP
The binary override file is fully compatible with
\fBdpkg-scanpackages\fR(1)\&. It contains four fields separated by spaces\&. The first field is the package name, the second is the priority to force that package to, the third is the section to force that package to and the final field is the maintainer permutation field\&.
.PP
The general form of the maintainer field is:
.sp
.if n \{\
.RS 4
.\}
.nf
old [// oldn]* => new
.fi
.if n \{\
.RE
.\}
.sp
or simply,
.sp
.if n \{\
.RS 4
.\}
.nf
new
.fi
.if n \{\
.RE
.\}
.sp
The first form allows a double\-slash separated list of old email addresses to be specified\&. If any of those are found then new is substituted for the maintainer field\&. The second form unconditionally substitutes the maintainer field\&.
.SH "THE SOURCE OVERRIDE FILE"
.PP
The source override file is fully compatible with
\fBdpkg-scansources\fR(1)\&. It contains two fields separated by spaces\&. The first field is the source package name, the second is the section to assign it\&.
.SH "THE EXTRA OVERRIDE FILE"
.PP
The extra override file allows any arbitrary tag to be added or replaced in the output\&. It has three columns, the first is the package, the second is the tag and the remainder of the line is the new value\&.
.SH "OPTIONS"
.PP
All command line options may be set using the configuration file, the descriptions indicate the configuration option to set\&. For boolean options you can override the config file by using something like
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
or several other variations\&.
.PP
\fB\-\-md5\fR, \fB\-\-sha1\fR, \fB\-\-sha256\fR
.RS 4
Generate the given checksum\&. These options default to on, when turned off the generated index files will not have the checksum fields where possible\&. Configuration Items:
APT::FTPArchive::\fIChecksum\fR
and
APT::FTPArchive::\fIIndex\fR::\fIChecksum\fR
where
\fIIndex\fR
can be
Packages,
Sources
or
Release
and
\fIChecksum\fR
can be
MD5,
SHA1
or
SHA256\&.
.RE
.PP
\fB\-d\fR, \fB\-\-db\fR
.RS 4
Use a binary caching DB\&. This has no effect on the generate command\&. Configuration Item:
APT::FTPArchive::DB\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Quiet; produces output suitable for logging, omitting progress indicators\&. More q\*(Aqs will produce more quiet up to a maximum of 2\&. You can also use
\fB\-q=#\fR
to set the quiet level, overriding the configuration file\&. Configuration Item:
quiet\&.
.RE
.PP
\fB\-\-delink\fR
.RS 4
Perform Delinking\&. If the
External\-Links
setting is used then this option actually enables delinking of the files\&. It defaults to on and can be turned off with
\fB\-\-no\-delink\fR\&. Configuration Item:
APT::FTPArchive::DeLinkAct\&.
.RE
.PP
\fB\-\-contents\fR
.RS 4
Perform contents generation\&. When this option is set and package indexes are being generated with a cache DB then the file listing will also be extracted and stored in the DB for later use\&. When using the generate command this option also allows the creation of any Contents files\&. The default is on\&. Configuration Item:
APT::FTPArchive::Contents\&.
.RE
.PP
\fB\-s\fR, \fB\-\-source\-override\fR
.RS 4
Select the source override file to use with the
sources
command\&. Configuration Item:
APT::FTPArchive::SourceOverride\&.
.RE
.PP
\fB\-\-readonly\fR
.RS 4
Make the caching databases read only\&. Configuration Item:
APT::FTPArchive::ReadOnlyDB\&.
.RE
.PP
\fB\-a\fR, \fB\-\-arch\fR
.RS 4
Accept in the
packages
and
contents
commands only package files matching
*_arch\&.deb
or
*_all\&.deb
instead of all package files in the given path\&. Configuration Item:
APT::FTPArchive::Architecture\&.
.RE
.PP
\fBAPT::FTPArchive::AlwaysStat\fR
.RS 4
\fBapt-ftparchive\fR(1)
caches as much as possible of metadata in a cachedb\&. If packages are recompiled and/or republished with the same version again, this will lead to problems as the now outdated cached metadata like size and checksums will be used\&. With this option enabled this will no longer happen as it will be checked if the file was changed\&. Note that this option is set to "false" by default as it is not recommend to upload multiply versions/builds of a package with the same versionnumber, so in theory nobody will have these problems and therefore all these extra checks are useless\&.
.RE
.PP
\fBAPT::FTPArchive::LongDescription\fR
.RS 4
This configuration option defaults to "true" and should only be set to
"false"
if the Archive generated with
\fBapt-ftparchive\fR(1)
also provides
Translation
files\&. Note that the
Translation\-en
master file can only be created in the generate command\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show a short usage summary\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Show the program version\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 4
Configuration File; Specify a configuration file to use\&. The program will read the default configuration file and then this configuration file\&. If configuration settings need to be set before the default configuration files are parsed specify a file with the
\fBAPT_CONFIG\fR
environment variable\&. See
\fBapt.conf\fR(5)
for syntax information\&.
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 4
Set a Configuration Option; This will set an arbitrary configuration option\&. The syntax is
\fB\-o Foo::Bar=bar\fR\&.
\fB\-o\fR
and
\fB\-\-option\fR
can be used multiple times to set different options\&.
.RE
.SH "EXAMPLES"
.PP
To create a compressed Packages file for a directory containing binary packages (\&.deb):
.sp
.if n \{\
.RS 4
.\}
.nf
\fBapt\-ftparchive\fR packages \fIdirectory\fR | \fBgzip\fR > Packages\&.gz
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBapt.conf\fR(5)
.SH "DIAGNOSTICS"
.PP
\fBapt\-ftparchive\fR
returns zero on normal operation, decimal 100 on error\&.
.SH "BUGS"
.PP
\m[blue]\fBAPT bug page\fR\m[]\&\s-2\u[1]\d\s+2\&. If you wish to report a bug in APT, please see
/usr/share/doc/debian/bug\-reporting\&.txt
or the
\fBreportbug\fR(1)
command\&.
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fBAPT team\fR
.RS 4
.RE
.SH "NOTES"
.IP " 1." 4
APT bug page
.RS 4
\%http://bugs.debian.org/src:apt
.RE
